main: dev.woofer.simpletracker.SimpleTracker
name: SimpleTracker
version: 1.0.0
description: Allows you to get the coordinates of a player.
api-version: 1.19
author: woofer
website: https://github.com/woofer300/SimpleTracker

commands:
  coords:
    description: A command that grabs the coordinates of a given player.
    permission: simpletracker.coords
    usage: /coords <username>

permissions:
  simpletracker.coords:
    default: true
    description: Use /coords.