main: dev.woofer.simpletracker.SimpleTracker
name: SimpleTracker
version: 1.0.0
description: Adds "/coords <username>" command which outputs a player's in-game coordinates.
api-version: 1.20
author: woofer

commands:
  coords:
    description: Grabs a player's coordinates.
    permission: simpletracker.coords
    usage: /coords <username>

permissions:
  simpletracker.coords:
    default: true
    description: Use /coords.